# Site settings
title: Sree Harsha Nelaturu
description: Deep Learning Researcher

baseurl: ""
url: "/"
email: nelaturu.harsha@gmail.com

# Social media
twitter: "Sree_Harsha_N"
github: "nelaturuharsha"
linkedin: "sreeharshanelat"
# orcid: "your-orcid-id"
# scholar: "https://scholar.google.com/citations?user=your-id"

# Pagination
paginate: 6
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# SCSS
sass:
  sass_dir: _sass
  style: compressed

# Include/Exclude
include:
  - _pages
  - _data

exclude:
  - README.md
  - LICENSE.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "_pages"
    values:
      layout: "page"

# Plugins
plugins:
  - jekyll-paginate
